name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        run: npm install
        working-directory: apps/backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: apps/frontend

      - name: Run backend tests with coverage
        run: |
          if npm run | grep -q 'test:coverage'; then
            npm run test:coverage
            npx istanbul check-coverage --branches 70 --functions 70 --lines 70 --statements 70
          else
            echo "Coverage check skipped"
          fi
        working-directory: apps/backend

      - name: Build frontend
        run: npm run build
        working-directory: apps/frontend

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "Missing RENDER_DEPLOY_HOOK_URL secret"
            exit 1
          fi
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
